In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [3]:
#1
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
#2
a_1 = a.reshape(3,4)

a_2 = a.reshape(2,6)

a_3 = a.reshape(4,3)

a_4 = a.reshape(6,2)

a_5 = a.reshape(12,1)

In [10]:
#3
a__1 = a.reshape(-1,4)

a__2 = a.reshape(-1,6)

a__3 = a.reshape(-1,3)

a__4 = a.reshape(6,-1)

a__5 = a.reshape(12,-1)

In [11]:
#4
print("Размерность массива 1х12:{}".format(a.ndim))
print("Размерность массива 12х1:{}".format(a_5.ndim))
#Ответ:нельзя

Размерность массива 1х12:1
Размерность массива 12х1:2


In [14]:
#5
b = np.random.randn(3,4)
br = b.flatten()

In [16]:
#6
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [17]:
#7
b = np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [20]:
#8
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.concatenate((a,b),axis=0)
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [31]:
#9
a = np.arange(12)
A = a.reshape(4,3)
At = A.T
B = np.dot(A,At)
print(B)
print(B.shape)
b = np.linalg.det(B)
if b == 0:
    print("Определитель матрицы равен 0,обратную матрицу нельзя вычислить")
else:
    bb = np.linalg.inv(B)
    print(bb)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
(4, 4)
Определитель матрицы равен 0,обратную матрицу нельзя вычислить


In [33]:
#10
np.random.seed(42)

In [35]:
#11
c = np.linspace(0,16,16,endpoint=False)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [52]:
#12
C = c.reshape(4,4)
D = B + C*10
print(D)
d = np.linalg.det(D)
print(d)
r = np.linalg.matrix_rank(D)
print(r)
D_inv = np.linalg.inv(D)
print(D_inv)

[[  5.  24.  43.  62.]
 [ 54. 100. 146. 192.]
 [103. 176. 249. 322.]
 [152. 252. 352. 452.]]
-7.685903354004529e-25
2
[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


In [53]:
#13
D_inv = np.where(D_inv < 0, 0, 1)
print(D_inv)
E = np.where(D_inv > 0, B, C)
print(E)            

[[1 1 0 1]
 [0 1 1 0]
 [1 0 0 1]
 [0 1 1 0]]
[[  5.  14.   2.  32.]
 [  4.  50.  86.   7.]
 [ 23.   9.  10. 212.]
 [ 12. 122. 212.  15.]]
